name = "chicko-api-proxy"
main = "src/index.ts"
compatibility_date = "2024-04-17"

[vars]
ENVIRONMENT = "production"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[[kv_namespaces]]
binding = "USERS"
id = "6f095f10194a45ec9cdcc98129fb2426"

[[kv_namespaces]]
binding = "MAGIC_LINKS"
id = "5519cb41b5554c51bf248dbecee1aa6a"
